#!/bin/bash
### Job Name
#PBS -N 033
### Project code
#PBS -A UIUC0021
#PBS -l walltime=06:00:00
#PBS -q regular
### Merge output and error files
#PBS -j oe
### Select 1 nodes with 1 CPUs 
#PBS -l select=1:ncpus=1
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M zzheng25@illinois.edu

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

### Run the executable
source /glade/work/$USER/personal_clone_name/bin/activate
python apply_model_members.py "033" "2006" "2015"
python apply_model_members.py "033" "2061" "2070"
