#!/bin/bash
### Job Name
#PBS -N ens_2061_odd
### Project code
#PBS -A your_project
#PBS -l walltime=12:00:00
#PBS -q regular
### Merge output and error files
#PBS -j oe
### Select 1 nodes with 36 CPUs 
#PBS -l select=1:ncpus=36
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M your_email@illinois.edu

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

### Run the executable
source /glade/work/$USER/personal_clone_name/bin/activate
python ens_2061_odd.py